version: "3.8"

services:
  erik_backend:
    container_name: erik_backend
    build:
      context: .
      dockerfile: ./.docker/backend/Dockerfile
    working_dir: /usr/src/erik_backend
    restart: on-failure
    ports:
      - 3000:3000
    volumes:
      - /usr/src/erik_backend/node_modules
      - ./:/usr/src/erik_backend
    networks:
      - erik_network

  erik_database:
    container_name: erik_database
    image: mysql:latest
    platform: linux/x86_64
    restart: on-failure
    volumes:
      - ./.docker/database/mysql:/var/lib/mysql
    ports:
      - 3360:3306
    environment:
      MYSQL_DATABASE: erik_database
      MYSQL_ROOT_PASSWORD: erik
      MYSQl_USER: erik
      MYSQL_PASSWORD: erik
    networks:
      - erik_network

networks:
  erik_network:
    driver: bridge
